export const EventTypes = {
  GET_EVENT: "GET_EVENT",
  GET_EVENTS: "GET_EVENTS",
  EVENT_LOADED: "EVENT_LOADED",
  EVENTS_LOADED: "EVENTS_LOADED",
  EVENT_DELETE: "EVENT_DELETE",
  CLEAR_EVENTS: "CLEAR_EVENTS",
  EVENT_ERROR: "EVENT_ERROR",
};
