export const ScoreTypes = {
  GET_SCORE: "GET_SCORE",
  GET_SCORES: "GET_SCORES",
  SCORE_LOADED: "SCORE_LOADED",
  SCORES_LOADED: "SCORES_LOADED",
  SCORE_DELETE: "SCORE_DELETE",
  CLEAR_SCORES: "CLEAR_SCORES",
  SCORE_ERROR: "SCORE_ERROR",
};
