export const TeamTypes = {
  GET_TEAM: "GET_TEAM",
  GET_TEAMS: "GET_TEAMS",
  TEAM_LOADED: "TEAM_LOADED",
  TEAMS_LOADED: "TEAMS_LOADED",
  TEAM_DELETE: "TEAM_DELETE",
  CLEAR_TEAMS: "CLEAR_TEAMS",
  TEAM_ERROR: "TEAM_ERROR",
};
