export const UserTypes = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_REQUEST_SUCCESS: "AUTH_REQUEST_SUCCESS",
  USER_LOADED: "USER_LOADED",
  USERS_LOADED: "USERS_LOADED",
  CLEAR_USER: "CLEAR_USER",
  UPDATE_USER: "UPDATE_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  AUTH_ERROR: "AUTH_ERROR",
  LOGOUT: "LOGOUT",
}
