export const userTypes = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_REQUEST_SUCCESS: 'AUTH_REQUEST_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',

  USER_LOADED: 'USER_LOADED',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',

  LOGOUT: 'LOGOUT'
};
